#region Usings

using System;
using System.Runtime.InteropServices;

#endregion

namespace FasmWrapper
{
    /// <summary>
    ///     The following structure has two variants - it either defines the line
    ///     that was loaded directly from source, or the line that was generated by
    ///     macroinstruction. First case has the highest bit of line_number set to 0,
    ///     while the second case has this bit set.
    ///     In the first case, the file_path field contains pointer to the path of
    ///     source file (empty string if it's the source that was provided directly to
    ///     fasm_Assemble function), the line_number is the number of line within
    ///     that file (starting from 1) and the file_offset field contains the offset
    ///     within the file where the line starts.
    ///     In the second case the macro_calling_line field contains the pointer to
    ///     LINE_HEADER structure for the line which called the macroinstruction, and
    ///     the macro_line field contains the pointer to LINE_HEADER structure for the
    ///     line within the definition of macroinstruction, which generated this one.
    /// </summary>
    [StructLayout(LayoutKind.Explicit)]
    public struct FasmLineHeader
    {
        [FieldOffset(0)]
        [MarshalAs(UnmanagedType.LPStr)]
        public string FilePath;

        [FieldOffset(4)]
        public uint LineNumber;

        [FieldOffset(8)]
        public uint FileOffset;

        [FieldOffset(8)]
        public uint MacroOffsetLine;

        [FieldOffset(12)]
        public IntPtr MacroLinePtr;

        /// <summary>
        ///     Returns the fully qualified type name of this instance.
        /// </summary>
        /// <returns>
        ///     A <see cref="T:System.String" /> containing a fully qualified type name.
        /// </returns>
        public override string ToString()
        {
            return String.Format("LineNumber: {0}", LineNumber);
        }
    }
}